# docker-compose.yml (исправленная версия)

services:
  discord-telegram-bot:
    build: .
    container_name: discord_notifier
    restart: always
    env_file:
      - .env
    volumes:
      # Монтируем именованный том в папку /app/data
      # Теперь бот сможет создать и использовать voice_stats.db внутри этой папки
      - db_data:/app/data
      # Монтируем папку логов, как и раньше
      - ./logs:/app/logs

volumes:
  # Объявляем именованный том для данных
  db_data:
